import { chromium } from 'playwright';

const url = 'http://127.0.0.1:4173/preview.html';
const executablePath = process.env.TAVERN_FORUM_BROWSER_PATH?.trim();
const browser = await chromium.launch({
    headless: true,
    ...(executablePath ? { executablePath } : {}),
});

try {
    const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
    await desktop.goto(url, { waitUntil: 'networkidle' });
    const visibleTextImages = await desktop.locator('.tf-feed-list .tf-text-image').count();
    if (visibleTextImages !== 1) throw new Error(`expected only intentional post images to display, found ${visibleTextImages}`);
    if (!/[\u3400-\u9fff]/u.test(await desktop.locator('.tf-text-image p').first().innerText())) throw new Error('text image description is not Chinese');
    const postOrder = await desktop.locator('.tf-post').first().evaluate(post => ({ caption: [...post.children].findIndex(node => node.classList.contains('tf-post-caption')), image: [...post.children].findIndex(node => node.classList.contains('tf-text-image') || node.classList.contains('tf-post-image')), actions: [...post.children].findIndex(node => node.classList.contains('tf-post-actions')) }));
    if (!(postOrder.caption < postOrder.image && postOrder.image < postOrder.actions)) throw new Error('post body, image and action order is incorrect');
    if (await desktop.getByText('文字配图', { exact: true }).count()) throw new Error('text image labels should stay hidden');
    if (await desktop.locator('.tf-post-image-editor').count()) throw new Error('post image editor should stay closed until explicitly requested');
    await desktop.screenshot({ path: 'preview.png' });
    await desktop.locator('[data-action="open-post"]').first().click();
    await desktop.screenshot({ path: 'preview-post-detail.png' });
    await desktop.locator('[data-action="back-post"]').click();
    await desktop.locator('.tf-feed-list [data-action="open-npc"]').first().click();
    await desktop.screenshot({ path: 'preview-public-profile.png' });
    await desktop.locator('[data-action="edit-npc"]').first().click();
    if (await desktop.locator('.tf-memory-card').count()) throw new Error('role memory should not stay embedded in the profile editor');
    await desktop.screenshot({ path: 'preview-role-profile.png' });
    await desktop.locator('.tf-topbar [data-tab="me"]').click();
    await desktop.screenshot({ path: 'preview-profile.png' });
    await desktop.locator('[data-action="me-section"][data-section="memory"]').click();
    if (!await desktop.locator('.tf-memory-card').count()) throw new Error('standalone role memory page is missing');
    await desktop.screenshot({ path: 'preview-role-memory.png' });
    await desktop.locator('.tf-settings-entry').click();
    await desktop.locator('[data-action="me-section"][data-section="boundaries"]').click();
    await desktop.screenshot({ path: 'preview-boundaries.png' });
    await desktop.locator('[data-action="me-section"][data-section="sources"]').click();
    await desktop.locator('[data-action="toggle-source-preset"]').check({ force: true });
    if (!await desktop.locator('[data-action="toggle-source-preset"]').isChecked()) throw new Error('preset source switch did not persist');
    if (!await desktop.evaluate(() => globalThis.SillyTavern.getContext().extensionSettings.tavern_forum.sources.sillyTavernPreset)) throw new Error('preset source setting did not persist');
    if (!await desktop.locator('[data-action="toggle-world-book"]').count()) throw new Error('world book master switch is missing');
    if (!await desktop.locator('.tf-world-bound-badge').count()) throw new Error('character-bound world book was not recognized');
    await desktop.screenshot({ path: 'preview-sources.png' });

    await desktop.locator('[data-action="me-section"][data-section="appearance"]').click();
    if (!await desktop.locator('[data-appearance-number="postOpacity"]').count()) throw new Error('post opacity control is missing');
    if (!await desktop.locator('[data-appearance-image-url="brandIcon"]').count()) throw new Error('brand icon control is missing');
    await desktop.locator('[data-action="restore-standard-css"]').click();
    if (!await desktop.locator('.tf-custom-css').inputValue().then(value => value.includes('微坛标准 CSS 美化模板'))) throw new Error('built-in CSS template was not loaded');
    await desktop.screenshot({ path: 'preview-appearance.png' });

    await desktop.locator('[data-action="me-section"][data-section="modules"]').click();
    if (await desktop.locator('[data-action="test-module-probability"]').count()) throw new Error('obsolete 100-run probability test should not be rendered');
    if (await desktop.locator('[data-action="toggle-module-injection"][data-module-id="forum"]').count()) throw new Error('forum injection switch should only exist on the main-chat injection page');
    if (!await desktop.getByText('主聊天读取论坛内容', { exact: true }).count()) throw new Error('forum card is missing its injection status summary');
    const nativeOptionStyle = await desktop.locator('select option').first().evaluate(option => {
        const style = getComputedStyle(option);
        return { color: style.color, background: style.backgroundColor };
    });
    const readableNativeOption = (nativeOptionStyle.color === 'rgb(38, 38, 38)' && nativeOptionStyle.background === 'rgb(255, 255, 255)')
        || (nativeOptionStyle.color === 'rgb(111, 54, 71)' && nativeOptionStyle.background === 'rgb(248, 231, 236)');
    if (!readableNativeOption) throw new Error(`native select menu colors are unreadable: ${JSON.stringify(nativeOptionStyle)}`);
    await desktop.locator('[data-module-id="forum"] [data-action="go-injection-settings"]').click();
    if (!await desktop.locator('[data-settings-block="chat-injection"]').count()) throw new Error('forum card did not open the centralized main-chat injection controls');
    if (!await desktop.getByText('论坛 → 正文', { exact: true }).count()) throw new Error('main-chat injection direction is not labelled');
    await desktop.waitForTimeout(40);
    const injectionOffset = await desktop.locator('[data-settings-block="chat-injection"]').evaluate((block) => {
        const view = block.closest('.tf-view');
        return block.getBoundingClientRect().top - view.getBoundingClientRect().top;
    });
    if (injectionOffset > 80) throw new Error(`main-chat injection controls were not focused after navigation (${injectionOffset}px)`);
    await desktop.screenshot({ path: 'preview-injection.png' });
    await desktop.locator('[data-action="me-section"][data-section="modules"]').click();
    await desktop.screenshot({ path: 'preview-settings-v3.png' });
    const travelToggle = desktop.locator('[data-action="toggle-world-module"][data-module-id="travel"]');
    if (!await travelToggle.isChecked()) await travelToggle.check({ force: true });
    const fortuneToggle = desktop.locator('[data-action="toggle-world-module"][data-module-id="fortune"]');
    if (!await fortuneToggle.isChecked()) await fortuneToggle.check({ force: true });
    const healthToggle = desktop.locator('[data-action="toggle-world-module"][data-module-id="health"]');
    if (!await healthToggle.isChecked()) await healthToggle.check({ force: true });
    const inventoryToggle = desktop.locator('[data-action="toggle-world-module"][data-module-id="inventory"]');
    if (!await inventoryToggle.isChecked()) await inventoryToggle.check({ force: true });
    if (await desktop.locator('[data-action="toggle-fortune-api-draw"]').isChecked()) throw new Error('AI fortune draw must be disabled by default');
    await desktop.locator('[data-action="open-module-context"][data-module-id="travel"]').click();
    if (await desktop.locator('.tf-pet-screen-menu').count() !== 1) throw new Error('in-device care menu is missing');
    if (await desktop.locator('.tf-companion-status [data-action="companion-care"]').count()) throw new Error('care actions should not be duplicated beside the device');
    if (await desktop.locator('[data-companion-field="avatarUrl"]').count()) throw new Error('companion avatar URL field should stay hidden');
    if (await desktop.getByText('寄回的见闻', { exact: true }).count()) throw new Error('companion travel log should stay hidden');
    await desktop.locator('[data-action="toggle-companion-profile"]').click();
    if (await desktop.locator('[data-action="choose-companion-species"]').count() !== 6) throw new Error('expected six built-in pixel companions');
    if (await desktop.locator('[data-action="choose-companion-device"]').count() !== 5) throw new Error('expected five device structures');
    await desktop.locator('[data-action="choose-companion-species"][data-species-id="fox"]').click();
    const callsBeforePet = await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls);
    await desktop.locator('[data-action="companion-care"][data-care="feed"]').last().click();
    if (await desktop.locator('[data-action="companion-feed-food"]').count() !== 6) throw new Error('pet food selector did not expose six foods inside the device');
    await desktop.locator('[data-action="companion-feed-food"][data-food-id="berry"]').click();
    const callsAfterPet = await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls);
    if (callsAfterPet !== callsBeforePet) throw new Error('local companion care unexpectedly called the API');
    if (await desktop.locator('[data-action="choose-companion-species"][data-species-id="fox"]').getAttribute('aria-pressed') !== 'true') throw new Error('pixel companion selection did not update species');
    if (!await desktop.locator('.tf-companion-v3.is-action-feed .tf-feed-drop').isVisible()) throw new Error('feed animation did not activate');
    await desktop.locator('[data-action="choose-companion-device"][data-device-skin="terminal"]').click();
    if (!await desktop.locator('.tf-companion-v3.is-device-terminal').count()) throw new Error('device structure selection did not persist');
    if (!await desktop.locator('.tf-companion-profile-card').evaluate(node => node.hasAttribute('open'))) throw new Error('companion profile collapsed after changing a device');
    await desktop.locator('[data-companion-environment="weather"]').selectOption('rain');
    await desktop.locator('[data-companion-environment="timeOfDay"]').selectOption('night');
    if (!await desktop.locator('.tf-companion-v3.is-weather-rain.is-time-night').count()) throw new Error('manual weather and room time did not update the pet screen');
    if (await desktop.locator('[data-companion-environment="weather"]').inputValue() !== 'rain') throw new Error('manual weather did not persist');
    await desktop.locator('.tf-companion-home').scrollIntoViewIfNeeded();
    await desktop.screenshot({ path: 'preview-companion.png' });
    await desktop.locator('.tf-companion-profile-card').scrollIntoViewIfNeeded();
    await desktop.screenshot({ path: 'preview-companion-profile.png' });

    await desktop.evaluate(() => { Math.random = () => 0; });
    await desktop.locator('[data-action="companion-depart-local"]').click();
    await desktop.locator('[data-action="companion-signal-local"]').click();
    await desktop.locator('[data-action="companion-return"]').click();
    if (!/背包/.test(await desktop.locator('.tf-pet-message').innerText())) throw new Error('companion return did not confirm souvenir inventory settlement');

    await desktop.locator('[data-action="back-world-home"]').click();
    await desktop.locator('[data-action="open-world-page"][data-module-id="inventory"]').click();
    if (!/返程/.test(await desktop.locator('.tf-world-board-page').innerText())) throw new Error('returned companion souvenir is missing from inventory');
    await desktop.locator('[data-action="back-world-home"]').click();
    await desktop.locator('[data-action="open-world-page"][data-module-id="fortune"]').click();
    if (await desktop.locator('[data-action="revoke-local-fortune"]').count()) await desktop.locator('[data-action="revoke-local-fortune"]').click();
    const callsBeforeFortune = await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls);
    await desktop.locator('[data-action="draw-local-fortune"]').first().click();
    if (!await desktop.locator('[data-action="revoke-local-fortune"]').count()) throw new Error('fortune revoke action is missing');
    await desktop.locator('[data-action="revoke-local-fortune"]').click();
    if (!await desktop.locator('[data-action="draw-local-fortune"]').count()) throw new Error('fortune did not return to the local draw state after revoke');
    if (await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls) !== callsBeforeFortune) throw new Error('local fortune draw or revoke unexpectedly called the API');

    await desktop.locator('[data-action="back-world-home"]').click();
    await desktop.locator('[data-action="open-world-page"][data-module-id="health"]').click();
    await desktop.locator('[data-action="create-local-health"]').click();
    if (!await desktop.locator('.tf-care-scene').count()) throw new Error('animated local health scene is missing');
    if (!await desktop.locator('.tf-care-room .tf-care-character.is-patient').count()) throw new Error('health scene is missing its patient character');
    if (!await desktop.locator('.tf-care-progress-label').count()) throw new Error('health scene progress has no readable label');
    if (await desktop.getByText('CARE MOMENT', { exact: true }).count()) throw new Error('old mixed-language health heading should not be rendered');
    await desktop.locator('[data-action="health-find-provider"]').first().click();
    if (!await desktop.locator('.tf-health-case-v3.is-stage-seeking').count()) throw new Error('health animation stage did not advance');
    if (!await desktop.locator('.tf-care-character.is-helper').count()) throw new Error('health provider did not enter the scene');
    await desktop.screenshot({ path: 'preview-health-v3.png' });

    await desktop.locator('.tf-settings-entry').click();
    await desktop.locator('[data-action="me-section"][data-section="moderation"]').click();
    if (await desktop.locator('[data-action="toggle-system-ai-admin"]').isChecked()) throw new Error('system AI administrator must be disabled by default');
    if (!await desktop.locator('[data-action="toggle-npc-reports"]').isChecked()) throw new Error('NPC report capability should be available by default');
    await desktop.screenshot({ path: 'preview-moderation-ai.png' });

    await desktop.locator('.tf-topbar [data-tab="messages"]').click();
    if (!await desktop.locator('.tf-companion-dm-avatar').count()) throw new Error('companion conversation should use the pet portrait instead of an initial avatar');
    await desktop.locator('[data-action="open-conversation"][data-conversation-id="dm-1"]').click();
    if (!await desktop.locator('.tf-dm-profile-link').count()) throw new Error('conversation header profile link is missing');
    const callsBeforeSend = await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls);
    await desktop.locator('#tf-dm-input').fill('我会避开东岸。');
    await desktop.locator('[data-action="send-dm"]').click();
    await desktop.waitForTimeout(30);
    const callsAfterSend = await desktop.evaluate(() => globalThis.SillyTavern.getContext().generateCalls);
    if (callsAfterSend !== callsBeforeSend) throw new Error('plain DM send unexpectedly called the API');
    await desktop.locator('[data-action="generate-dm-reply"]').click();
    await desktop.waitForFunction(before => globalThis.SillyTavern.getContext().generateCalls > before, callsAfterSend);
    await desktop.screenshot({ path: 'preview-messages.png' });
    await desktop.locator('.tf-dm-profile-link').click();
    if (!await desktop.locator('.tf-public-profile').count()) throw new Error('conversation profile link did not open the role home page');
    await desktop.screenshot({ path: 'preview-dm-profile.png' });
    await desktop.locator('[data-action="close"]').last().click();
    const fab = desktop.locator('#tavern-forum-fab');
    const fabBox = await fab.boundingBox();
    if (!fabBox) throw new Error('floating launcher is missing');
    await desktop.mouse.move(fabBox.x + fabBox.width / 2, fabBox.y + fabBox.height / 2);
    await desktop.mouse.down();
    await desktop.mouse.move(fabBox.x - 70, fabBox.y - 55, { steps: 4 });
    await desktop.mouse.up();
    const savedFabPosition = await desktop.evaluate(() => globalThis.SillyTavern.getContext().extensionSettings.tavern_forum.ui.floatingButtonPosition);
    if (!Number.isFinite(savedFabPosition?.x) || !Number.isFinite(savedFabPosition?.y)) throw new Error('floating launcher position was not saved');

    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
    await mobile.goto(url, { waitUntil: 'networkidle' });
    await mobile.addStyleTag({ content: 'html { height: 0 !important; transform: translateZ(0); } body { position: fixed; inset: 0; height: 100dvh; }' });
    if (!await mobile.locator('#tavern-forum-root').isVisible()) throw new Error('mobile forum did not open from the floating launcher');
    const mobileRootBox = await mobile.locator('#tavern-forum-root').boundingBox();
    if (!mobileRootBox || mobileRootBox.height < 800) throw new Error(`mobile forum collapsed to ${mobileRootBox?.height || 0}px under a transformed zero-height root`);
    await mobile.locator('[data-action="close"]').last().click();
    await mobile.locator('#tavern-forum-menu-item').dispatchEvent('touchend');
    if (!await mobile.locator('#tavern-forum-root').isVisible()) throw new Error('mobile extension menu touch did not open the forum');
    await mobile.screenshot({ path: 'preview-mobile.png' });
    await mobile.locator('.tf-mobile-main-nav [data-tab="me"]').click();
    await mobile.locator('.tf-settings-entry').click();
    await mobile.locator('[data-action="me-section"][data-section="modules"]').click();
    const mobileSettingsNav = mobile.locator('.tf-settings-page .tf-me-nav');
    await mobileSettingsNav.evaluate(node => { node.scrollLeft = Math.min(260, node.scrollWidth - node.clientWidth); });
    const settingsNavScrollBefore = await mobileSettingsNav.evaluate(node => node.scrollLeft);
    await mobile.locator('[data-action="me-section"][data-section="sources"]').evaluate(node => node.click());
    await mobile.waitForTimeout(80);
    const settingsNavScrollAfter = await mobile.locator('.tf-settings-page .tf-me-nav').evaluate(node => node.scrollLeft);
    if (settingsNavScrollBefore > 20 && Math.abs(settingsNavScrollAfter - settingsNavScrollBefore) > 8) throw new Error(`switching settings reset horizontal navigation from ${settingsNavScrollBefore} to ${settingsNavScrollAfter}`);
    await mobile.screenshot({ path: 'preview-settings-mobile.png' });
    await mobile.locator('[data-action="me-section"][data-section="modules"]').evaluate(node => node.click());
    const mobileTravelToggle = mobile.locator('[data-action="toggle-world-module"][data-module-id="travel"]');
    if (!await mobileTravelToggle.isChecked()) await mobileTravelToggle.check({ force: true });
    await mobile.locator('[data-action="open-module-context"][data-module-id="travel"]').click();
    const mobileConsoleBox = await mobile.locator('.tf-pet-console').boundingBox();
    if (!mobileConsoleBox || mobileConsoleBox.width > 370) throw new Error('mobile companion console overflowed the viewport');
    await mobile.locator('.tf-view').evaluate(node => { node.scrollTop = Math.min(480, node.scrollHeight - node.clientHeight); });
    const mobileScrollBefore = await mobile.locator('.tf-view').evaluate(node => node.scrollTop);
    await mobile.locator('[data-action="companion-care"][data-care="pet"]').first().evaluate(node => node.click());
    await mobile.waitForTimeout(80);
    const mobileScrollAfter = await mobile.locator('.tf-view').evaluate(node => node.scrollTop);
    if (mobileScrollBefore > 80 && Math.abs(mobileScrollAfter - mobileScrollBefore) > 8) throw new Error(`mobile interaction changed scroll from ${mobileScrollBefore} to ${mobileScrollAfter}`);
    await mobile.screenshot({ path: 'preview-companion-mobile.png', fullPage: true });
    await mobile.locator('[data-action="back-world-home"]').click();
    await mobile.locator('.tf-mobile-main-nav [data-tab="home"]').click();
    const mobileStories = mobile.locator('.tf-stories');
    await mobileStories.evaluate(node => { node.scrollLeft = Math.min(160, node.scrollWidth - node.clientWidth); });
    const storiesScrollBefore = await mobileStories.evaluate(node => node.scrollLeft);
    await mobile.locator('[data-action="feed-mode"][data-feed="latest"]').evaluate(node => node.click());
    await mobile.waitForTimeout(80);
    const storiesScrollAfter = await mobile.locator('.tf-stories').evaluate(node => node.scrollLeft);
    if (storiesScrollBefore > 20 && Math.abs(storiesScrollAfter - storiesScrollBefore) > 8) throw new Error(`switching feed reset stories scroll from ${storiesScrollBefore} to ${storiesScrollAfter}`);
    await mobile.locator('.tf-view').evaluate(node => { node.scrollTop = Math.min(620, node.scrollHeight - node.clientHeight); });
    const homeScrollBeforePost = await mobile.locator('.tf-view').evaluate(node => node.scrollTop);
    await mobile.locator('[data-action="open-post"]').first().evaluate(node => node.click());
    await mobile.screenshot({ path: 'preview-post-detail-mobile.png' });
    await mobile.locator('[data-action="back-post"]').click();
    await mobile.waitForTimeout(80);
    const homeScrollAfterPost = await mobile.locator('.tf-view').evaluate(node => node.scrollTop);
    if (homeScrollBeforePost > 80 && Math.abs(homeScrollAfterPost - homeScrollBeforePost) > 8) throw new Error(`leaving post reset home scroll from ${homeScrollBeforePost} to ${homeScrollAfterPost}`);
    await mobile.locator('.tf-mobile-main-nav [data-tab="messages"]').click();
    if (!await mobile.locator('.tf-dm-list').isVisible()) throw new Error('mobile conversation list is not visible');
    await mobile.screenshot({ path: 'preview-messages-list-mobile.png' });
    await mobile.locator('[data-action="open-conversation"]').first().click();
    if (!await mobile.locator('.tf-dm-chat').isVisible() || await mobile.locator('.tf-dm-list').isVisible()) throw new Error('mobile chat did not replace the conversation list');
    await mobile.screenshot({ path: 'preview-messages-chat-mobile-v9.png' });
    await mobile.locator('[data-action="back-dm-list"]').click();
    await mobile.locator('[data-action="message-mode"][data-mode="notifications"]').click();
    await mobile.screenshot({ path: 'preview-notifications-mobile.png' });
} finally {
    await browser.close();
}
